name: BuildAfterCommit

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore NuGet Packages
        run: nuget restore $Env:GITHUB_WORKSPACE\FFLogsEasyCheck.sln
      - name: Building Project
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\FFLogsEasyCheck.sln
